---
- name: "Install additional resources"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install zip"
      become: true
      community.general.pacman:
        name: 
          - man
          - make
          - patch
          - unzip
          - postgresql-libs
          - zip
        state: present
    - name: "Install xclip"
      become: true
      community.general.pacman:
        name: 
          - xclip
        state: present
