---
- name: "Install additional resources"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install zip"
      become: true
      community.general.pacman:
        name: 
          - make
          - unzip
          - zip
        state: present
