---
- name: "Install development environment"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install python3-venv"
      become: true
      ansible.builtin.apt:
        name: python3-venv
        state: present
        update_cache: yes

    - name: "Install fish shell repository"
      become: true
      become_method: sudo
      ansible.builtin.apt_repository:
        repo: ppa:fish-shell/release-3
        state: present

    - name: "Install fish shell"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: fish
        state: present
        update_cache: yes

    - name: "Set fish as default shell"
      become: true
      become_method: sudo
      user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/fish

    - name: "Initial start fish"
      ansible.builtin.shell:
        cmd: fish -c 'echo test'
        creates: "{{ ansible_env.HOME }}/.config/fish/config.fish"

    - name: "Add ansible to fish path"
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "fish_add_path {{ ansible_env.HOME }}/.local/bin"

    - name: "Install fisher"
      ansible.builtin.shell:
        cmd: fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"

    - name: "Install bobthefish theme"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install oh-my-fish/theme-bobthefish'
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/bobthefish_display_colors.fish"

    - name: "Install z"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install jethrokuan/z'
        creates: "{{ ansible_env.HOME }}/.config/fish/conf.d/z.fish"

    - name: "Install fzf dependencies"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        pkg:
          - fzf
          - fd-find
          - bat
        state: present
        update_cache: yes

    - name: "Install fzf"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install PatrickF1/fzf.fish'
        creates: "{{ ansible_env.HOME }}/.config/fish/conf.d/fzf.fish"

    - name: "Add suport for nerd font"
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "set -g theme_nerd_fonts yes"
    
