---
- name: "Install development environment"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install fish shell"
      become: true
      community.general.pacman:
        name: fish
        state: present

    - name: "Set fish as default shell"
      become: true
      become_method: sudo
      user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/fish

    - name: "Initial start fish"
      ansible.builtin.shell:
        cmd: fish -c 'echo test'
        creates: "{{ ansible_env.HOME }}/.config/fish/config.fish"

    - name: "Install fisher"
      ansible.builtin.shell:
        cmd: fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"

    - name: "Install catppuccin theme"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install catppuccin/fish && fish_config theme save "Catppuccin Frappe"' 
        creates: "{{ ansible_env.HOME }}/.config/fish/themes/Catpuccin Frappe.theme"

    - name: "Install bass"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install edc/bass'
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/bass.fish"

    - name: "Install z"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install jethrokuan/z'
        creates: "{{ ansible_env.HOME }}/.config/fish/conf.d/z.fish"

    - name: "Install fzf dependencies"
      become: true
      become_method: sudo
      community.general.pacman:
        name:
          - fzf
          - fd
          - bat
        state: present

    - name: "Install fzf"
      ansible.builtin.shell:
        cmd: fish -c 'fisher install PatrickF1/fzf.fish'
        creates: "{{ ansible_env.HOME }}/.config/fish/conf.d/fzf.fish"

