
---
- name: "Install node"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install nvm"
      ansible.builtin.shell:
        cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: "Add nvm function to fish"
      copy:
        dest: "{{ ansible_env.HOME }}/.config/fish/functions/nvm.fish"
        content: |
          function nvm
            bass source ~/.nvm/nvm.sh --no-use ';' nvm $argv
          end

    - name: "Install node.js lts release"
      ansible.builtin.shell:
        cmd: fish -c 'nvm install --lts'
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
