---
- name: "Install development environment"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Import GPG key"
      ansible.builtin.shell:
        cmd: gpg --recv-keys E3FF2839C048B25C084DEBE9B26995E310250568

    - name: "Download python 3.8 rep"
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/python38.git"
        dest:  "{{ ansible_env.HOME }}/downloads/python38"

    - name: "Build and install python 3.8 package"
      ansible.builtin.shell:
        cmd: makepkg -is --noconfirm
        chdir: "{{ ansible_env.HOME }}/downloads/python38"
