---
- name: "Install development environment"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install python deadsnakes repository"
      become: true
      become_method: sudo
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: "Install python 3.8"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: python3.8
        state: present
        update_cache: yes

    - name: "Install python 3.8 venv"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: python3.8-venv
        state: present

    - name: "Install python 3.8 dev"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: python3.8-dev
        state: present

    - name: "Add postgresql client"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: postgresql-client
        state: present

    - name: "Add development packages"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        pkg:
          - libjpeg-dev
          - libldap2-dev
          - libpq-dev
          - libsasl2-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
        state: present
