---
- name: "Install rails development environment"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Checkout rbenv"
      ansible.builtin.shell:
        cmd: "git clone https://github.com/rbenv/rbenv.git {{ ansible_env.HOME }}/.rbenv"
        creates: "{{ ansible_env.HOME }}/.rbenv"

    - name: "Compile bash extension"
      ansible.builtin.shell:
        cmd: "cd {{ ansible_env.HOME }}/.rbenv && src/configure && make -C src"
        creates: "{{ ansible_env.HOME }}/.rbenv/src/realpath.o"

    - name: "Add rbenv to fish path"
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "set -Ux fish_user_paths $HOME/.rbenv/bin $fish_user_paths"

    - name: "rbenv init"
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "status --is-interactive; and rbenv init - fish | source"

    - name: "Create Plugins Path"
      file:
        path: "{{ ansible_env.HOME }}/.rbenv/plugins"
        state: directory

    - name: "Checkout ruby-build"
      ansible.builtin.shell:
        cmd: "git clone https://github.com/rbenv/ruby-build.git {{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
        creates: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"

    - name: "Install gem dependencies"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - libffi-dev
          - libglib2.0-dev

    - name: "Install nvm"
      ansible.builtin.shell:
        cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: "Install bass"
      ansible.builtin.shell:
        cmd: fish -c 'omf install bass'
        creates: "{{ ansible_env.HOME }}/.local/share/omf/pkg/bass"

    - name: "Add nvm function to fish"
      copy:
        dest: "{{ ansible_env.HOME }}/.config/fish/functions/nvm.fish"
        content: |
          function nvm
            bass source ~/.nvm/nvm.sh --no-use ';' nvm $argv
          end

    - name: "Install node.js lts release"
      ansible.builtin.shell:
        cmd: fish -c 'nvm install --lts'
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"

    - name: "Install python 2.7"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: python2.7
        state: present
        update_cache: yes

    - name: "Install google chrome package"
      become: true
      become_method: sudo
      ansible.builtin.apt:
        deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
        state: present

    - name: "Download chromedriver"
      ansible.builtin.shell:
        cmd: curl -o {{ ansible_env.HOME }}/downloads/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(google-chrome --version | egrep -o "[0-9]{3}" | egrep -m 1 -o "[0-9]{3}"))/chromedriver_linux64.zip
        creates: "{{ ansible_env.HOME }}/downloads/chromedriver.zip"

    - name: "Unpack"
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/downloads/chromedriver.zip"
        dest: "{{ ansible_env.HOME }}/.local/bin"
        creates: "{{ ansible_env.HOME }}/.local/bin/chromedriver"
