- name: "Copy files from templates"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "add tmux template"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/tmux/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"

    - name: "add fish template"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/fish/config.fish"
        dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"

    - name: "add neovim template"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/templates/neovim/"
        dest: "{{ ansible_env.HOME }}/.config/nvim"

