---
- name: "Install vim"
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "Install neovim"
      become: true
      become_method: sudo
      community.general.pacman:
        name: 
          - neovim
          - python-pynvim
        state: present

    - name: "Install c compiler"
      become: true
      become_method: sudo
      community.general.pacman:
        name: 
          - gcc
        state: present

    - name: "Install tools for telescope"
      become: true
      become_method: sudo
      community.general.pacman:
        name: 
          - ripgrep 
        state: present

    - name: "Python language server"
      ansible.builtin.pip:
        name: 
          - black
          - ropevim
          - pynvim

